website/auth.py
from flask import Blueprint, render_template, flash, redirect, url_for, session, request
from .models import User
from . import db, oauth, GOOGLE_CLIENT_ID, CLIENT_SECRET

auth = Blueprint('auth', __name__)

google = oauth.register(
    'google',
    client_id = GOOGLE_CLIENT_ID,
    client_secret = CLIENT_SECRET,
    server_metadata_url = 'https://accounts.google.com/.well-known/openid-configuration',
    client_kwargs={'scope': 'openid profile email'}
)

@auth.route('/signin', methods=['GET', 'POST'])
def signin():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            # if check_password_hash(user.password, password):
            if user.password == password:
                 flash('Logged in successfully!', category='success')
                 return redirect('userprofile')
            else:
                flash('Incorrect Password', category='error')
        else:
            flash(' Email doesn\'t exist', category='error')
    return render_template("signin.html", boolean=True)

@auth.route('/login_google')
def login_google():
    redirect_uri = url_for('auth.authorize', _external=True)
    return oauth.google.authorize_redirect(redirect_uri)

@auth.route('/signup_google')
def sign_up_google():
    redirect_uri = url_for('auth.authorize', _external=True)
    return oauth.google.authorize_redirect(redirect_uri)

@auth.route('/authorize')
def authorize():
    google = oauth.google
    token = google.authorize_access_token()
    resp = token['userinfo']

    session.clear()

    print(resp)
    session['name'] = resp['name']
    session['email'] = resp['email']
    session['obool'] = True
    return redirect('userprofile')

@auth.route('/logout')
def logout():
    session.clear()
    return redirect('/')

@auth.route('/userprofile')
def userprofile():
    name = session['name']
    email = session['email']
    oauth = session['obool']
    user = User.query.filter_by(email=email).first()
    if not user:
        newUser = User(email=email, name=name, oauth=oauth)
        db.session.add(newUser)
        db.session.commit()
    return redirect('/feed')

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        fname = request.form.get('fname')
        lname = request.form.get('lname')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        name = fname + " " + lname

        user = User.query.filter_by(email=email).first()

        if user:
            flash('Email already exists', category='error')
        elif len(email) < 4:
            flash('Email must be valid.', category='error')
        elif len(name) < 3:
            flash('First Name must be more than two characters.', category='error')
        elif password1 != password2:
            flash('Your passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            #add user
            newUser = User(email=email, name=name, password=password1, oauth=False)
            db.session.add(newUser)
            db.session.commit()
            session['name'] = name
            session['email'] = email
            flash('Account Created', category='success')

            return redirect('userprofile')

    return render_template("signup.html")

website/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from sqlalchemy import *
from .models import *

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("index.html")

@views.route('/about')
def about():
    return render_template("about.html")

@views.route('/contact')
def contact():
    return render_template("contact.html")


@views.route('/disciplines', methods=['POST', 'GET'])
def disciplines():
    disciplines = db.session.scalars(select(Discipline).order_by(Discipline.disc_id)).all()
    print(disciplines)
    discArray = []
    for discipline in disciplines:
        numDegrees = Degree.query.filter_by(disc_ID = discipline.disc_id).count()
        disc = {'id': discipline.disc_id, 'name': discipline.name, 'numDeg': numDegrees}
        discArray.append(disc)
    
    return render_template('disciplines.html', discArray = discArray)

@views.route('/degrees/<disc_id>')
def degrees(disc_id):
    degrees = db.session.scalars(select(Degree).where(Degree.disc_ID == disc_id)).all()
    degArray = []
    for degree in degrees:
        numCourses = Course.query.filter_by(degree_id = degree.deg_id).count()
        deg = {'id': degree.deg_id, 'name': degree.name, 'numCourses': numCourses}
        degArray.append(deg)
    
    return render_template('degrees.html', degArray = degArray)

@views.route('/courses/<deg_id>')
def courses(deg_id):
    courses = db.session.scalars(select(Course).where(Course.degree_id == deg_id)).all()
    courseArray = []
    for course in courses:
        numPosts = Post.query.filter_by(course_id = course.course_id).count()
        crs = {'id': course.degree_id, 'name': course.name, 'numPosts': numPosts}
        courseArray.append(crs)
    
    return render_template('courses.html', courseArray = courseArray)

@views.route('/posts/<course_id>', methods=['GET', 'POST'])
def posts(course_id):
    session['course_id'] = course_id
    posts = db.session.scalars(select(Post).where(Post.course_id == course_id)).all()
    postArray = []
    user = None
    if session and 'email' in session:
        user = User.query.filter_by(email=session['email']).first()
    

    for post in posts:
        numComments = Comment.query.filter_by(post_id = post.post_id).count()
        cmt = {'id': post.post_id, 'name': post.title, 'numComments': numComments, 'post_time': post.post_time, 'posterid': post.poster}
        print(cmt)
        postArray.append(cmt)

    if request.method == 'POST':
        poster = user.id
        title = request.form.get('title')
        content = request.form.get('content')

        newPost = Post(poster=poster, course_id=course_id, title=title, content=content)
        db.session.add(newPost)
        db.session.commit()
        
        return redirect(url_for('views.post', post_id = newPost.post_id))

    return render_template("posts.html", postArray = postArray, userid = user.id if user else 0)

@views.route('/post/<post_id>', methods=['GET', 'POST'])
def post(post_id):
    session['post_id'] = post_id
    post = Post.query.filter_by(post_id = post_id).first()
    author = User.query.filter_by(id=Post.poster).first()
    print(post)
    comments = db.session.scalars(select(Comment).where(Comment.post_id == post_id)).all()
    users = User.query.all()
    user = None

    for comment in comments:
        for user in users:
            if comment.commenter == user.id:
                comment.real_name = user.name

    if request.method == 'POST':
        user = User.query.filter_by(email=session['email']).first()
        commenter = user.id
        content = request.form.get('content')

        newPost = Comment(commenter=commenter, post_id=post_id, content=content)
        db.session.add(newPost)
        db.session.commit()

        return redirect(url_for('views.post', post_id = post_id))
    
    if session and 'email' in session:
        user = User.query.filter_by(email=session['email']).first()
    else:
        user = None

    return render_template("post.html", post = post, author=author, comments = comments, userid = user.id if user else 0)

@views.route('/deletepost/<post_id>')
def deletepost(post_id):
    cmtstmt = delete(Comment).where(Comment.post_id == post_id)
    db.session.execute(cmtstmt)
    stmt = delete(Post).where(Post.post_id == post_id)
    db.session.execute(stmt)
    db.session.commit()

    return redirect(url_for('views.posts', course_id = session['course_id']))

@views.route('/deletecomment/<comment_id>')
def deletecomment(comment_id):
    cmtstmt = delete(Comment).where(Comment.comment_id == comment_id)
    db.session.execute(cmtstmt)
    db.session.commit()

    return redirect(url_for('views.post', post_id = session['post_id']))

@views.route('/feed', methods=["POST", 'GET'])
def feed():
    user = User.query.filter_by(email=session['email']).first()
    users = User.query.all()
    posts = db.session.scalars(select(FeedPost)).all()

    for post in posts:
        for user in users:
            if post.poster_id == user.id:
                post.real_name = user.name
    
    if request.method=='POST':
        content=request.form.get('feedpost')

        newPost = FeedPost(poster_id = user.id, post_content = content)
        db.session.add(newPost)
        db.session.commit()

    return render_template("feed.html", username = user.name, feedposts = posts )

website/templates/degrees.html
{% extends "base.html" %}
{% include 'smallheader.html' %}

{% block container %}
    {% if degArray %}
        <div class="container">
            <h1 class="container-header">Degrees</h1>
        {% for deg in degArray %}
            <div class="discipline row">
                <div class="discipline-title"><a href={{url_for('views.courses', deg_id = deg.id)}}>{{deg.name}}</a></div>
                <hr />
                <div class="discipline-body">
                    <p class="left">Courses: {{deg.numCourses}}</p>
                    <p class="right">Recently updated: 10/02/2023 4:03 PM</p>
                </div>
            </div>
        {% endfor %}
        </div>
    {% endif %}

{% endblock %}
        <!----JavaScript for toggle menu---->
        <script>
            var navLinks = document.getElementById("navLinks");

            function showMenu() {
                navLinks.style.right = "0";
            }

            function hideMenu() {
                navLinks.style.right = "-200px";
            }
        </script>
        <!-- MDB -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"></script>

website/templates/disciplines.html
        {% extends "base.html" %}
        {% include 'smallheader.html' %}

        {% block container %}
        {% if discArray %}
            <div class="container">
                <h1 class="container-header">Disciplines</h1>
            {% for disc in discArray %}
                <div class="discipline row">
                    <div class="discipline-title"><a href={{url_for('views.degrees', disc_id = disc.id)}}>{{disc.name}}</a></div>
                    <hr />
                    <div class="discipline-body">
                        <p class="left">Degrees: {{disc.numDeg}}</p>
                        <p class="right">Recently updated: 10/02/2023 4:03 PM{{disc.time}}</p>
                    </div>
                </div>
            {% endfor %}
            </div>
        {% endif %}
        {% endblock %}
        
        <!----JavaScript for toggle menu---->
        <script>
            var navLinks = document.getElementById("navLinks");

            function showMenu() {
                navLinks.style.right = "0";
            }

            function hideMenu() {
                navLinks.style.right = "-200px";
            }
        </script>
        <!-- MDB -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"></script>
    </body>
</html>

website/templates/feed.html
{% extends 'base.html' %}
{% include 'smallheader.html' %}
{% block container %}
<!-- -------------- navbar close-------- -->
<div class="feedcontainer">
    <!-- -------left-sidebar------------ -->
        <div class="left-sidebar">
            <div class="sidebar-profile-box">
                <div class="sidebar-profile-info">
                    <img src={{url_for('static' , filename = 'images/network.png')}}>
                    <h1>{{username}}</h1>
                    <h3>Major</h3>
                    <ul>
                        <li>Your posts<span>5</span></li>
                        <li>Your Buddies<span>10</span></li>
                    </ul>
                </div>
            </div>
    
            <div class="sidebar-activity" id="sidebarActivity">
                <h3>RECENT</h3>
                <a href="#"><img src={{url_for('static' , filename = 'images/recent.png')}}> Web Development</a>
                <a href="#"><img src={{url_for('static', filename = "images/recent.png")}}> Software Engineering</a>
                <a href="#"><img src={{url_for('static', filename = "images/recent.png")}}> Calculus II</a>
                <a href="#"><img src={{url_for('static', filename = "images/recent.png")}}> Data Structure</a>
    
                <h3>GROUPS</h3>
                <a href="#"><img src={{url_for('static', filename = "images/group.png")}}> Web Development Group</a>
                <a href="#"><img src={{url_for('static', filename = "images/group.png")}}> Intro to Computer Science Group</a>
                <a href="#"><img src={{url_for('static', filename = "images/group.png")}}> Math Group</a>
                <a href="#"><img src={{url_for('static', filename = "images/group.png")}}> HTML & CSS Learners</a>

                <h3>HASHTAG</h3>
                <a href="#"><img src={{url_for('static', filename = "images/hashtag.png")}}> webdevelopment</a>
                <a href="#"><img src={{url_for('static', filename = "images/hashtag.png")}}> userinterface</a>
                <a href="#"><img src={{url_for('static', filename = "images/hashtag.png")}}> onlinelearning</a>
                <div class="group-search-link">
                    <a href="groupsearch.html">Find a Group</a>
                </div>
            </div>
        </div>

        <!-- -----------------main-content------------ -->
<div class="main-content">

    <div class="create-post">
        <form class="feedpost" method="POST">
            <div class="create-post-input">
                <img src={{url_for('static', filename = "images/network.png")}}>
                <textarea name="feedpost" id="feedpost" rows="2" placeholder="Write a post"></textarea>
            </div>
            <div class="create-post-links">
                <li><img src={{url_for('static', filename = "images/photo.png")}}>Photo</li>
                <li><img src={{url_for('static', filename = "images/video.png")}}>Video</li>
                <li><img src={{url_for('static', filename = "images/event.png")}}>Groups</li>
                <li><button class="nostyle feedpost">Post</button></li>
            </div>
        </form>
    </div>
    <div class="sort-by">
        <hr>
        <p>Sort by: <span>top <img src={{url_for('static', filename = "images/down-arrow.png")}}></span></p>
    </div>

    {%if feedposts%}
        {% for post in feedposts %}
            <div class="post">
                <div class="post-author">
                    <img src={{url_for('static', filename = "images/josh.png")}}>
                    <div>
                        <h1>{{post.real_name}}</h1>
                        <small>{{post.post_time}}</small>
                    </div>
                </div>
                <p>{{post.post_content}}</p>
                <div class="post-stats">
                    <div>
                        <img src={{url_for('static', filename = "images/thumbsup.png")}}>
                        <img src={{url_for('static', filename = "images/love.png")}}>
                        <img src={{url_for('static', filename = "images/clap.png")}}>
                        <span class="liked-users">Adam and 6 others</span>
                    </div>
                    <div>
                        <span>99 comments</span>
                    </div>
                </div>
                <div class="post-activity">
           
                    <div class="post-activity-link">
                        <img src={{url_for('static', filename = "images/like.png")}}>
                        <span>Like</span>
                    </div>
                    <div class="post-activity-link">
                        <img src={{url_for('static', filename = "images/comment.png")}}>
                        <span>Comment</span>
                    </div>
                    <div class="post-activity-link">
                        <img src={{url_for('static', filename = "images/share.png")}}>
                        <span>Share</span>
                    </div>
                    <div class="post-activity-link">
                        <img src={{url_for('static', filename = "images/send.png")}}>
                        <span>Message</span>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <div class="post">
        <div class="post-author">
            <img src={{url_for('static', filename = "images/adam.png")}}>
            <div>
                <h1>Adam Dauda</h1>
                <small>Computer Science Major | Software Engineering Concentration</small>
                <small>2 hours ago</small>
            </div>
        </div>
        <p>Hi, I am Adam Dauda. I am a Senior at University of North Carolina at Charlotte. I am having issues with my Info privacy class, can someone help me out? </p>
        <img src={{url_for('static', filename = "images/s3.jpeg")}} width="100%">

        <div class="post-stats">
            <div>
                <img src={{url_for('static', filename = "images/thumbsup.png")}}>
                <img src={{url_for('static', filename = "images/love.png")}}>
                <img src={{url_for('static', filename = "images/clap.png")}}>
                <span class="liked-users">Adam Dauda and 4 others</span>
            </div>
            <div>
                <span>2 comments</span>
            </div>
        </div>
        <div class="post-activity">
            <div class="post-activity-link">
                <img src={{url_for('static', filename = "images/like.png")}}>
                <span>Like</span>
            </div>
            <div class="post-activity-link">
                <img src={{url_for('static', filename = "images/comment.png")}}>
                <span>Comment</span>
            </div>
            <div class="post-activity-link">
                <img src={{url_for('static', filename = "images/share.png")}}>
                <span>Share</span>
            </div>
            <div class="post-activity-link">
                <img src={{url_for('static', filename = "images/send.png")}}>
                <span>Message</span>
            </div>
        </div>
    </div>
    
    <div class="post">
        <div class="post-author">
            <img src={{url_for('static', filename = "images/cayden.png")}}>
            <div>
                <h1>Cayden Renegar</h1>
                <small>Computer Science Major | Software Engineering Concentration</small>
                <small>2 hours ago</small>
            </div>
        </div>
        <p></p>
        <img src={{url_for('static', filename = "images/s1.jpeg")}} width="100%">

        <div class="post-stats">
            <div>
                <img src={{url_for('static', filename = "images/thumbsup.png")}}>
                <img src={{url_for('static', filename = "images/love.png")}}>
                <img src={{url_for('static', filename = "images/clap.png")}}>
                <span class="liked-users">Josh and 4 others</span>
            </div>
            <div>
                <span>22 comments</span>
            </div>
        </div>
        <div class="post-activity">
        
            <div class="post-activity-link">
                <img src={{url_for('static', filename = "images/like.png")}}>
                <span>Like</span>
            </div>
            <div class="post-activity-link">
                <img src={{url_for('static', filename = "images/comment.png")}}>
                <span>Comment</span>
            </div>
            <div class="post-activity-link">
                <img src={{url_for('static', filename = "images/share.png")}}>
                <span>Share</span>
            </div>
            <div class="post-activity-link">
                <img src={{url_for('static', filename = "images/send.png")}}>
                <span>Send</span>
            </div>
        </div>
    </div>

</div>

<!-- ------------right-sidebar--------------- -->
<div class="right-sidebar">
    <div class="sidebar-news">
        <img src={{url_for('static', filename = "images/more.png")}} class="info-icon">
        <h3>Suggested Groups</h3>
        <a href="#">Intro to Info Security and Privacy</a>
        <span>1d ago &middot; 50 Buddies</span>

        <a href="#">Computing Professionals II</a>
        <span>19h ago &middot; 10 Buddies</span>

        <a href="#">Human Centered Design</a>
        <span>1d ago &middot; 37 Buddies</span>

        <a href="#">Comp & Their Impact on Society</a>
        <span>18h ago &middot; 12 Buddies</span>

        <a href="groupsearch.html" class="read-more-link">Read More</a>
    </div>

    
    <div class="sidebar-useful-links">
        <a href={{url_for('views.about')}}>About</a>
        <a href="#">Accessiblity</a>
        <a href="#">Help Center</a>
        <a href="#">Privacy Policy</a>
        <a href="#">Advertising</a>
        <a href="#">More</a>

        <div class="copyright-msg">
            <img src={{url_for('static', filename = "images/logo3.png")}}>
            <p>CampusBuddies &#169; 2023. All right reserved</p>
        </div>
    </div>

</div>
</div>

<script>

    let profileMenu = document.getElementById("profileMenu");

    function toggleMenu(){
        profileMenu.classList.toggle("open-menu");
    }

</script>

<script>

    let sideActivity = document.getElementById("sidebarActivity");
    let moreLink = document.getElementById("showMoreLink");

    function toggleActivity(){
        sideActivity.classList.toggle("open-activity");

        if(sideActivity.classList.contains("open-activity")){
            moreLink.innerHTML = "Show less <b>-</b>";
        }
        else{
            moreLink.innerHTML = "Show more <b>+</b>";
        }
    }

</script>

{% endblock %}

website/templates/logout.html
{% extends "base.html" %}
{% block title%}Logout{% endblock %}
{% block container %}

{% endblock %}

website/templates/nav.html
<nav>
    <a href="./"><img src="../static/images/logo.png"></a>
    <div class="nav-links" id="navLinks">  
        <i class="fa fa-close" onclick="hideMenu()"></i>
        <ul>
            <li><a href="./">HOME</a></li>
            <li><a href="./disciplines">FORUMS</a></li>
            <li><a href="./about">ABOUT</a></li>
            <li><a href="./contact">CONTACT</a></li>
            <li><a href="./signin">SIGN IN</a></li>
            <li><a href="./signup">SIGN UP</a></li>
        </ul>
    </div>
    <i class="fa fa-bars" onclick="showMenu()"></i>
</nav>

website/templates/post.html
{% extends "base.html" %}
{% include 'smallheader.html' %}

{% block container %}
<!--<h1>{{userid}}</h1>-->
    <div class="container">
        <div class="discipline row">
            <div class="discipline-title">{{post.title}}<!-- (Poster Id: {{author.id}})--></div>
            
            <div class="discipline-body">
                <p class="left">{{author.name}}</p>
                <p class="right">Posted: {{post.post_time}}</p>
                <div class="discipline-body">
                    <hr style="clear: both;" />
                    <p class="post-content">{{post.content}}</p>
                </div>
            </div>
        </div>

        <div class="comments">
            {% if comments %}
                {% for comment in comments %}
                    <div class="discipline row">
                        <div class="discipline-title"></div>
                        
                        <div class="discipline-body">
                            <p class="left">{{comment.real_name or comment.commenter}}<!-- (Commenter Id: {{comment.commenter}})--></p>
                            <p class="right">Posted: {{comment.comment_time.strftime('%m/%d/%Y %H:%M')}}</p>
                            <div class="discipline-body">
                                <hr style="clear: both;" />
                                <p class="post-content">{{comment.content}}</p>
                                <!--<p>{{userid}}</p>-->
                                {% if userid == comment.commenter %}
                                    <hr/>
                                    <a href="{{url_for('views.deletecomment', comment_id = comment.comment_id)}}" class="deletepost btn right btn-danger"><small>Delete</small></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
                    
            <div class="createComment hidden">
                <form method="POST">
                    <textarea id="content" name="content" rows="5"></textarea>
                    <br/>
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div> 
        
            <button class="createCommentbtn btn btn-primary">Make a new comment</button>
        </div> 
    </div>
    
        <!----JavaScript for toggle menu---->
        <script>
            var navLinks = document.getElementById("navLinks");

            function showMenu() {
                navLinks.style.right = "0";
            }

            function hideMenu() {
                navLinks.style.right = "-200px";
            }

            const newCommentButton = document.querySelector('.createCommentbtn');
            const commentBox = document.querySelector('.createComment');

            newCommentButton.addEventListener('click', makeNewPost);

            function makeNewPost(){
                commentBox.classList.remove('hidden');
                newCommentButton.classList.add('hidden');
            }
        </script>
        <!-- MDB -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"></script>
{% endblock %}

website/templates/posts.html
{% extends "base.html" %}
{% include 'smallheader.html' %}

{% block container %}
{% if postArray %}
<!--<h1>{{userid}}</h1>-->
<div class="container">
    <h1 class="container-header">Posts</h1>
    {% for post in postArray %}
        <div class="discipline row">
            <div class="discipline-title">
                <a href={{url_for('views.post', post_id=post.id)}}>{{post.name}}</a><!-- (Poster Id: {{post.posterid}})-->
                {% if userid == post.posterid %}
                    <a href="{{url_for('views.deletepost', post_id = post.id)}}" class="deletepost btn right btn-danger"><small>Delete</small></a>
                {% endif %}
            </div>
            <hr />
            <div class="discipline-body">
                <p class="left">Comments: {{post.numComments}}</p>
                <p class="right">{{post.post_time.strftime('%m/%d/%Y %H:%M')}}</p>
            </div>
        </div>
    {% endfor %}
{% endif %}


    <div class="createPost hidden">
        <form method="POST">
            <input type="text" name="title" id="title" placeholder="Title">
            <br />
            <textarea id="content" name="content" rows="5" ></textarea>
            <br />
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>


    <button class="createPostbtn btn btn-primary">Make a new post</button>
</div>
<!----JavaScript for toggle menu---->
<script>
    var navLinks = document.getElementById("navLinks");

    function showMenu() {
        navLinks.style.right = "0";
    }

    function hideMenu() {
        navLinks.style.right = "-200px";
    }

    newPostButton = document.querySelector('.createPostbtn');
    postBox = document.querySelector('.createPost');

    newPostButton.addEventListener('click', makeNewPost);

    function makeNewPost() {
        postBox.classList.remove('hidden');
        newPostButton.classList.add('hidden');
        // newPostButton.classList.remove('btn');
    }
</script>
<!-- MDB -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"></script>

{% endblock %}

website/templates/smallheader.html
<nav class="navbar">
    <div class="navbar-left">
        <a href="{{url_for('views.home')}}" class="logo"><img src="{{url_for('static', filename="images/logo3.png")}}"></a>

        <div class="search-box">
            <img src="{{url_for('static', filename="images/search.png")}}">
            <input type="text" placeholder="Search">
        </div>

    </div>
    <div class="navbar-center">
        <ul>
            <li><a href="{{url_for('views.home')}}"><img src="{{url_for('static', filename="images/home.png")}}"> <span>Home</span></a></li>
            <li><a href="{{url_for('views.disciplines')}}"><img src="{{url_for('static', filename="images/buddies.png")}}"> <span>Forums</span></a></li>
            <li><a href="#"><img src="{{url_for('static', filename="images/buddies.png")}}"> <span>Buddies</span></a></li>
            <li><a href="#"><img src="{{url_for('static', filename="images/message.png")}}"> <span>Messaging</span></a></li>
            <li><a href="#"><img src="{{url_for('static', filename="images/notification.png")}}"> <span>Notifications</span></a></li>
        </ul>
    </div>
    <div class="navbar-right">
        <div class="online">
            <img src="{{url_for('static', filename="images/network.png")}}" class="nav-profile-img" onclick="toggleMenu()">
        </div>
    </div>

    <!-- --------------- profile-drop-down-menu---------- -->
    <div class="profile-menu-wrap" id="profileMenu">
        <div class="profile-menu">
            <div class="user-info">
                <img src={{url_for('static', filename="images/network.png")}}>
                <div>
                    <h3>{{session.name}}</h3>
                    <a href="{{url_for('views.feed')}}">See your profile</a>
                </div>
            </div>
            <hr>
            <a href="#" class="profile-menu-link">
                <img src="{{url_for('static', filename="images/setting.png")}}">
                <p>Settings & Privacy</p>
                <span>></span>
            </a>
            <a href="#" class="profile-menu-link">
                <img src="{{url_for('static', filename="images/help.png")}}">
                <p>Help & Support</p>
                <span>></span>
            </a>
            <a href="{{url_for('auth.logout')}}" class="profile-menu-link logout">
                <img src="{{url_for('static', filename="images/logout.png")}}">
                <p>Logout</p>
                <span>></span>
            </a>
        </div>
    </div>

</nav>

<script>
    let profileMenu = document.getElementById("profileMenu");

    function toggleMenu(){
        profileMenu.classList.toggle("open-menu");
    }

    let sideActivity = document.getElementById("sidebarActivity");
    let moreLink = document.getElementById("showMoreLink");

    function toggleActivity(){
        sideActivity.classList.toggle("open-activity");

        if(sideActivity.classList.contains("open-activity")){
            moreLink.innerHTML = "Show less <b>-</b>";
        }
        else{
            moreLink.innerHTML = "Show more <b>+</b>";
        }
    }

    let logoutbtn = document.querySelector('.logout');
    logoutbtn.addEventListener('click', logout)
    function logout(){
        window.cookie = "";
    }
</script>